### ISSUE TITLE
console.log can be kind of spammy

### ISSUE THREAD

**Issue by ckknight** [woutervh-/typescript-is#10]
This isn't a huge concern, but when running the transformer with webpack, my console gets spammed with line after line of `typescript-is: transforming program with 893 source files; using TypeScript 3.3.1.`

https://github.com/woutervh-/typescript-is/blob/master/src/transform-inline/transformer.ts#L7

**Comment by woutervh-** [comment]
hi @ckknight 

You're, it can be kind of spammy. I will remove the `console.log` be default and add an option to enabled "verbose" logging

**Comment by woutervh-** [comment]
https://github.com/woutervh-/typescript-is/commit/7c8f4ce26efd690756074503dd9d9d21bc80cf1a
Release `0.9.3`

**Comment by ckknight** [comment]
Fantastic, thank you.
