### ISSUE TITLE
This module should not be used in runtime. Instead, use a transformer during compilation.

### ISSUE THREAD

**Issue by jtremback** [woutervh-/typescript-is#14]
I just wanted to drop this in here for your information. I don't know the root cause, or whether this issue even belongs in this repo but I thought it might be helpful for you to know about this.

When running with `ts-node-dev --compiler ttypescript --respawn --transpileOnly src/index.ts`, I get the error `This module should not be used in runtime. Instead, use a transformer during compilation.` when the validator runs. I don't get the error in parts of the program where the validator is not running.

Removing the `--transpileOnly` fixes the problem.

**Comment by woutervh-** [comment]
hi @jtremback 

The error you mentioned only happens when the transformer from `typescript-is` is not used. The default implementation is to throw a run-time error.
I'm not exactly sure why the transformer is not used, but as you mentioned that removing the `--transpileOnly` flag resolved the issue, I'm guessing that this option causes `ts-node-dev` to skip the transformation part.
Digging a bit further into `ts-node-dev` this option sounds like it causes the compiler to strip out the type checking part and just emit JS code. That would definitely prevent `typescript-is` from transforming the code and generating type guards, because it needs the type information to do this.

I hope this clarifies the situation. There is not much I can do if the entire type checking part of compilation is skipped.

Is there anything else you'd like to have clarified?

Thanks!

**Comment by woutervh-** [comment]
Closing for housekeeping purposes.

**Comment by jtremback** [comment]
Thanks @woutervh- !

**Comment by mtiller** [comment]
I got this same error when trying to run `jest` tests.  I added the `plugins` section to my `tsconfig.json`, but perhaps `ts-jest` is somehow overriding those settings?!?

**Comment by woutervh-** [comment]
Hi @mtiller 

I'm not sure how `ts-jest` runs the compiler. Sounds like there should be some configuration in `ts-jest` to enable `ttypescript` or vice versa. Maybe there is some info on these two repos about how to do it.

**Comment by mtiller** [comment]
I ran into this issue again.  I found that if I added:

```
globals: {
    "ts-jest": {
      compiler: "ttypescript"
    }
  }
```

...to my `jest.config.js` file, the issue went away.

**Comment by yanshiyason** [comment]
@mtiller Thank you for sharing!!

**Comment by bergkvist** [comment]
I'm still getting this error running `npm start` 
```
Error: This module should not be used in runtime. Instead, use a transformer during compilation.
```

My package.json:

```json
{
  "scripts": {
     "start": "ts-node-dev --compiler ttypescript --respawn src/index.ts"
  },
  "dependencies": {
    "typescript": "^3.8.3"
  },
  "devDependencies": {
    "ts-node-dev": "^1.0.0-pre.44",
    "ttypescript": "^1.5.10",
    "typescript-is": "^0.15.0"
  }
}
```

My tsconfig.json:

```json
{
  "compilerOptions": {
    "plugins": [
      { "transform": "typescript-is/lib/transform-inline/transformer" }
    ],
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

**Comment by nevillco** [comment]
I'm also seeing this on a new Node project. The `verbose` flag confirms the plugin is running (I get `typescript-is: transforming program with 287 source files; using TypeScript 4.2.4.`), but then still receive `This module should not be used in runtime. Instead, use a transformer during compilation` at runtime. Not sure if I'm missing something or something is broken.

`package.json`:
```
{
  "scripts": {
    "lint": "eslint . --ext .ts",
    "build": "npm run lint && npm run npx ttsc",
    "serve": " firebase use develop && npm run build && firebase emulators:start --only auth,functions,firestore",
    "deploy": "firebase deploy --only functions",
    "test": "env TS_NODE_COMPILER_OPTIONS='{\"module\": \"commonjs\" }' mocha -r ts-node/register 'test/tests/**/*.ts'"
  },
  "engines": {
    "node": "12"
  },
  "main": "lib/index.js",
  "dependencies": {
    ...
    "reflect-metadata": "^0.1.13",
    "typescript-is": "^0.18.2"
  },
  "devDependencies": {
    ...
    "ts-node": "^9.1.1",
    "ts-node-dev": "^1.1.6",
    "ttypescript": "^1.5.12",
    "typescript": "^4.2.4"
  },
  "private": true
}
```
`tsconfig.json`:
```
{
  "compilerOptions": {
    "baseUrl": "./src",
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "allowJs": false,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "forceConsistentCasingInFileNames": true,
    "plugins": [
      {
        "transform": "typescript-is/lib/transform-inline/transformer",
        "verbose": true,
      },
    ]
  },
  "include": [
    "src/**/*",
  ],
  "compileOnSave": true,
}
```

**Comment by genesst** [comment]
Any updates on this one? Facing the same issue.

**Comment by francescov1** [comment]
Any solution for this? Still running into it
