### ISSUE TITLE
[Feature Request] use custom error when throwing assertions

### ISSUE THREAD

**Issue by andykais** [woutervh-/typescript-is#19]
It would be nice if the error thrown from assertType and createAssertType used a custom error and exposed that error from the library.

Currently my code using assertions looks like this:
```js
// assert.ts
const assertConfigType = (config: any) => {
  try {
    assertType<Config>(config)
  } catch (e) {
    throw new RuntimeTypeError(e.message)
  }
}
// further up the stack
try {
  ...
} catch (e) {
  if (e instanceof RuntimeTypeError) {
    console.log('poorly formed config given')
    console.log(e.message)
    process.exit(1)
  }
}
```

It would be nice if I could simplify the code to this:
```js
// assert.ts
const assertConfigType = (config: any) => assertType<Config>(config)

// further up the stack
import { RuntimeTypeError } from 'typescript-is'
try {
  ...
} catch (e) {
    if (e instanceof RuntimeTypeError) {
      ...
    }
}
```

For reference, `node-fetch` does this with the `FetchError` class https://www.npmjs.com/package/node-fetch#class-fetcherror

**Comment by woutervh-** [comment]
Hi @andykais 
Thanks for the suggestion,
Totally makes sense to me, and seems like an easy change. I will implement this and update the issue when it's released.

**Comment by woutervh-** [comment]
Hi @andykais 

I have released version `0.10.5`.
The class is called `TypeGuardError` and you can import it from the library:

```typescript
import {TypeGuardError, assertType} from 'typescript-is';

try {
  assertType<..>(..);
} catch (error) {
  if (error instanceof TypeGuardError) {
    ..
  }
}
```

Let me know if it's working or not.

**Comment by andykais** [comment]
I can confirm! One weird thing though, the name of the error class is still `Error`, not `TypeGuardError`

```ts
export const assertConfigType = (configInit: any) => {
  try {
    assertType<ConfigInit>(configInit)
  } catch (e) {
    console.log('e.name', e.name)
    // e.name Error
    console.log('is instance', e instanceof TypeGuardError)
    // is instance true
    throw e
  }
}
```

**Comment by andykais** [comment]
more reference:
```ts
import { FetchError } from 'node-fetch'

const fetchError = new FetchError('','','')
console.log('fetchError.name', fetchError.name)
// fetchError.name FetchError

class TestErrorName extends Error {
  name = 'TestErrorName'
}
const testErrorName = new TestErrorName()
console.log('testErrorName.name', testErrorName.name)
// testErrorName.name TestErrorName
```

**Comment by woutervh-** [comment]
Ah I guess it's one of these weird quirks in JavaScript, you have to give it a name explicitly, I will make a fix for it hopefully tomorrow. 👀

**Comment by woutervh-** [comment]
Released version `0.10.6` with name set to "TypeGuardError".

**Comment by andykais** [comment]
I dont think the package was actually published, npm still shows `0.10.5` as the most recent

**Comment by woutervh-** [comment]
Oops, my bad, should be published now 😵

**Comment by andykais** [comment]
haha! I can confirm its working. As always, thanks for your work!
