### ISSUE TITLE
Reject superfluous properties sometimes but not always

### ISSUE THREAD

**Issue by LoganDark** [woutervh-/typescript-is#22]
Sometimes I want to verify if an object has a key without rejecting everything else. Sometimes I want to verify an object has a key and nothing else. Configuring this at the transformer level can be too broad.

**Comment by LoganDark** [comment]
Maybe you should have a `has()` function that works like `is()` but ignores superfluous properties?

**Comment by woutervh-** [comment]
Hi @LoganDark 

Perhaps the `is` and `assert` family of functions can have additional options to overwrite the setting.
Would that be useful?

E.g.

```typescript
is<A>(obj, { disallowSuperfluousProperties: false }) // overwrites setting from `tsconfig.json`
```

**Comment by LoganDark** [comment]
@woutervh- Putting that in an if statement would be rediculous.

I feel like the `disallowSuperfluousProperties` option should be deprecated, and instead use `is`, which disallows superfluous properties, and `has`, which doesn't. So `assertIs` and `assertHas` would also be a thing. Would that work?

**Comment by woutervh-** [comment]
Hi @LoganDark 

I like to keep the current `is` as-is (pun intended) for two reasons:

1. If I change the default behavior of existing functions it'll be a breaking change (I will consider it for version `1.0.0`)
2. I like that `is` closely resembles the `is-a` relationship, i.e. `is<Animal>(cat)` means `cat is an animal`. I.e. it follows the "assignability" relationship in TypeScript: `cat is assignable to Animal`.

The `disallowSuperfluousProperties` option makes the `is` family of functions symmetric and it becomes more of an equivalence relationship, Maybe something like `typeEquals` or `isExactly` sounds reasonable?

**Comment by LoganDark** [comment]
@woutervh- maybe instead of `is` and `has` do `equals` and `is` respectively? keep the old behavior for is but add equals

**Comment by woutervh-** [comment]
@LoganDark 
`equals` sounds good, I'll add that in. I'll keep you posted.

**Comment by woutervh-** [comment]
Hi @LoganDark 

I've released version `0.12.0`, updated the read me as well.
Release: https://github.com/woutervh-/typescript-is/releases/tag/v0.12.0

Let me know if it works for you.
Thanks!

**Comment by LoganDark** [comment]
@woutervh- Thanks, works perfectly!

**Comment by LoganDark** [comment]
You should also consider adding a second argument for config overrides, but this issue isn't that.
