### ISSUE TITLE
[Request] add a changelog

### ISSUE THREAD

**Issue by andykais** [woutervh-/typescript-is#24]
Hi! I saw that a new version was published just a few days ago, though its hard to say that that release actually changed (though I did my best to dig through the commits). It would be awesome if you started keeping a [CHANGELOG.txt](https://keepachangelog.com/en/1.0.0/) or used [github releases](https://help.github.com/en/articles/creating-releases) for future versions so we can see what new features/fixes/breaking changes are part of that release.

Of course, its more work to maintain, but it helps you (the maintainer) look back on what you have done over time too.

This may help, this may not, but on one of my personal projects (of which I am using `typescript-is` 🎈!) I automate the process of publishing so that travis ci runs `npm publish` for me upon creating a github release https://github.com/andykais/scrape-pages/blob/319dd19b0c952bd9b72ba4f23b3995c25fc6bd81/.travis.yml

**Comment by woutervh-** [comment]
Hi @andykais 

Indeed it's a good idea. I've never used Github releases, but I like it when other OSS projects use it. I've just been too lazy to figure out how it works :) I guess now is the time to find out.

I'll make sure to created a release log using Github releases with the next release I make, then will close this issue ;)

**Comment by woutervh-** [comment]
First try: https://github.com/woutervh-/typescript-is/releases/tag/v0.12.0

**Comment by andykais** [comment]
nice! Some tips if you are interested (follow whatever feels right though!)

Common convention for github releases is to leave the title as the [version](https://github.com/gcanti/io-ts/releases) and give headers to:

### New Features
### Breaking Changes
### Bug fixes

**Comment by woutervh-** [comment]
Fixed ;)
