### ISSUE TITLE
Usage in linked modules

### ISSUE THREAD

**Issue by hernyo** [woutervh-/typescript-is#26]
When developing a module we often `npm link` it to a parent application for testing. This way we temporarily rely on the parent app's compiler - which has neither `ttypescript`, nor it checks the linked module's `tsconfig` file -> meaning it will not run the transformer and `is<...>` will not be generated. This way it's pretty much impossible to develop using `npm link` unless I'm missing something.

Do you have an idea for this situation?

**Comment by woutervh-** [comment]
Hi @hernyo 

I'm not sure if I understand the set up for the problem. Is it something like this?

```shell
~/parent$ npm link
~/child$ npm link parent
~/child$ tsc # ---> error because parent is using is<...>(...)
```

**Comment by hernyo** [comment]
Yes, almost, just the other way around. Just to make sure we're on the same page:
`~/reusable-ui-component$ npm link`
`~/main-web-app$ npm link reusable-ui-component`
`~/main-web-app$ npm start`

This compiles fine, but does not transform `is<...>(...)` so it will throw a runtime error when calling it.

**Comment by hernyo** [comment]
Putting some more thought into this, it would be useful if we had a manually ran build step to generate the transformations, save them in a separate file and check them in with the source. And another bonus build step which makes sure the previously generated transformation files match the current interfaces - this could be simple, just generate the file contents again and compare with the existing files.

This would be very similar to what was discussed in issue #7

**Comment by woutervh-** [comment]
Hi @hernyo 

So if I understand correctly, you are importing TypeScript files directly from `reusable-ui-component` into `main-web-app`? Because in that case you have two options:

- You can set up TypeScript with `tsconfig` and `ttypescript` configured to transform the files, or
- you can compile the TypeScript source files in `reusable-ui-component` and export the `.js` and `.d.ts` files which can then be included by `main-web-app`

Something similar to #7 can also be done, but it will essentially require a compile build step, in the same way the second option I listed does.

**Comment by hernyo** [comment]
Normally we're not importing the TS code directly. The module's build script compiles it and we publish the compiled code - so normally we're fine.

However, while we're developing/debugging `reusable-component`, we use `npm link` to link the component to the main app - and this is the situation when we import the TS code directly. Workaround could be temporarily commenting that line of code (uh..) or modifying the parent app build scripts to include the transformer (uhh....).

In this case being able to precompile the type checker methods would be more than helpful. Yep, something similar to #7. 

Thanks!

**Comment by woutervh-** [comment]
Hi @hernyo 

I think it will take me quite a while to get the feature described in #7 to work.
As a work around solution I would suggest to do one of the following:

- Enable the transformer in any project that needs to compile TypeScript code with functions from `typescript-is`
- Compile the source code with functions from `typescript-is` and import the compiled JS and type definitions.

I will post again when I make some progress on the feature of #7.

**Comment by hernyo** [comment]
Hi @woutervh- 

last week I've put some thought into how this could work for us. The basic idea was to have a script which precompiles the `is<...>` calls so the compiled code can be checked in to the source and then integrate another script in the build to make sure the interfaces hasn't changed since the files were compiled last time.

Ended up with this:
- wrap the required `is<...>` calls into validator functions and place them all in a file, suffix it with `.exclude.ts`
- exclude these files from being compiled
- create a script which compiles only these files into an `outdir = ./tmp`
- rename the validators from `.exclude.js` to `.compiled.js`, copy them into the original source folder and check them in to source control
- remove the `tmp` folder
- require the `.compiled.js` files and use the validator functions from there
- this script has to be ran manually every time someone changes the public interface

- in addition to this, create a script which compiles the validators and checks if resulting files are the same as the ones checked in to the source. This can be used as a safety net if someone forgets to compile the validators - then the build fails due to outdated validator files

Not the nicest solution and it's not completely ready yet.

I was wondering if there could be a way to automatically figure out which validators to compile; unfortunately decorators cannot be used for interfaces and I didn't feel like adding an extra member just for the sake of identification.

**Comment by woutervh-** [comment]
Sounds like quite a lot of effort. I'm wondering though: if you're going through these steps to get some specific code compiled and used by the main web app, wouldn't it be just as easy (easier?) to compile the whole project and then import the compiled code into the main web app altogether?

**Comment by hernyo** [comment]
Agreed, it's a lot of effort, especially knowing that the compiled / published module actually works without these steps - only the `npm link`'ed module won't work.

Note that it's not the main web app which would use the compiled validator code: it's the `reusable-component` itself. However we cannot develop the `reusable-component` as it is, it needs to be embedded in a host app during development: and this is done by `npm link` - which helps us propagate the code changes in `reusable-component` to the main app instantly without recompiling, packing / publishing, installing the component. But then we rely on the main app's build system: it would be easy to change it to use `ttsc` but in our case the main app is a large application and we don't want / cannot change its build system just for the sake of our team. I'll see if I can come up with a useful idea in the near future.

**Comment by hernyo** [comment]
To be more specific, precompiling the validators does not sound like a problem to me. It's just the solution I described is way too complicated (exclude files from build, then build them to a temp folder, copy, compare, etc...)

**Comment by woutervh-** [comment]
Closing for housekeeping.
