### ISSUE TITLE
Usage without ttypescript?

### ISSUE THREAD

**Issue by zackify** [woutervh-/typescript-is#30]
Is there a way to manually run a transform and import the transformed code for this library? I'm using create-react-app and don't want to eject in order to change my webpack loaders

**Comment by woutervh-** [comment]
Hi @zackify 

Yes, it's technically possible to do this without `ttypescript`, but it can be cumbersome.
The transformer is exported here:
https://github.com/woutervh-/typescript-is/blob/master/src/transform-inline/transformer.ts
You may import it and use it however you wish.

One example of how this is used is in the `debug.ts` file:
https://github.com/woutervh-/typescript-is/blob/master/debug/debug.ts
There the project is configured manually without `ttypescript`.

**Comment by woutervh-** [comment]
Closing for house keeping.
