### ISSUE TITLE
Add option to work in transpiled source

### ISSUE THREAD

**Issue by zdila** [woutervh-/typescript-is#33]
For much faster development we use `transpileOnly` option and do typechecking in different background thread. Unfortunately this library fails with this option (see #14).

It would be great to add an option to skip type checking in such a case. Then `assertType` would never throw, `is` would always return `true`, etc.

We could achieve this by hacking `typescript-is/index.js`:
```typescript
function assertType(obj, getErrorMessage = () => null) {
...

function is(obj, getErrorMessage = () => null) {
...

function createIs(getErrorMessage = () => null) {
...

function createAssertType(getErrorMessage = () => null) {
...
```

I hope you understand what do I mean :-)

**Comment by woutervh-** [comment]
Hi @zdila,

In the options there is `shortCircuit` which does what you're looking for: it will always return true and never throw an error.

 https://github.com/woutervh-/typescript-is/blob/master/README.md#options

Is this sufficient for your situation?

I have seen your PR, but I'm on holiday until the 15th of September, so I can't do any review until then.

Thanks!

**Comment by zdila** [comment]
Thanks for the info. I've overlooked `shortCircuit` option but it still causes `This module should not be used in runtime. Instead, use a transformer during compilation.` error for transpiled source.

**Comment by woutervh-** [comment]
Hi @zdila, 

Right, I forgot the `shortCircuit` option will only work if the transformer is actually used. I'm afraid I'll have to look into this when I'm back from my holiday then.

Thanks for your patience.

**Comment by woutervh-** [comment]
Release as `v0.12.5`

https://github.com/woutervh-/typescript-is/releases/tag/v0.12.5
