### ISSUE TITLE
Feature request: support .enforce<SomeType>() syntax

### ISSUE THREAD

**Issue by dko-slapdash** [woutervh-/typescript-is#41]
Hi. 

Currently, to wrap some async request call with the library, one has to write:

```
const res = assertType<{
  name: string;
  age?: number;
}>(await client.request(
  “https://example.com”,
  { some_post_data: 123, other: “abc” }
));
```

It doesn’t look nice:
1. Too many nested parens. 
2. The response shape goes before the request shape which is counter-intuitive. 

A way better syntax would be:

```
const res = await client
  .request(
    “https://example.com”,
    { some_post_data: 123, other: “abc” }
  )
  .enforce<{
    name: string;
    age?: number;
  }>();
```

(This is how Prettier would format it.)

Is it possible to implement this .postfix-like syntax in the transformer?

Notice 3 things here:
1. The whole purpose is to let it work with promises. Without working with promises such syntax is pretty useless since it produces nested parens again.
2. It’s okay for request() to return something custom (in terms of typing information), like a promise with additional enforce() method in it (along with .then and .catch - `Promise<T> & EnforcePromiseMixin<T>`)), it’s easily expressible in TS I guess. 
3. If the validation fails, it’s critical to have a detailed error message with all the info about mismatching properties. 

If it’s possible to implement such a thing (is it possible in theory at all?), it would be a huge relief IMHO. There is no other library which supports such things.

**Comment by woutervh-** [comment]
Hi @dko-slapdash 

Using promises is something on the road map: https://github.com/woutervh-/typescript-is#%EF%B8%8F-road-map

However in your situation you could also try using `createAssertType<T>()`:

```typescript
const res = await client
  .request(
    “https://example.com”,
    { some_post_data: 123, other: “abc” }
  )
  .then<createAssertType<{
    name: string;
    age?: number;
  }>());
```

Is this acceptable?

**Comment by dko-slapdash** [comment]
Interesting, thanks! Of course in terms of syntax cleaniness,

```
.then(createAssertType<{
  name: string;
  age?: number;
}>());
```

looks more special-character-swamped than 

```
.createAssertType<{
  name: string;
  age?: number;
}>();
```

(the last removes `then(` and `)`) - but I think you're right, it's not too critical.

**Comment by dko-slapdash** [comment]
@woutervh- I still want to return back to this topic since I read the source code of the library a little. In particular, 

1. This is how the shortest possible syntax looks like currently (formatted with default Prettier): <img src="https://user-images.githubusercontent.com/46383452/78986768-eb781580-7ae0-11ea-8a00-3e5f49758d32.png" width="300" />
2. This is how the ideal (shortest possible) syntax would look like: <img src="https://user-images.githubusercontent.com/46383452/78986849-16626980-7ae1-11ea-85cc-bafce33d520c.png" width="300" />
3. This place: https://github.com/woutervh-/typescript-is/blob/master/src/transform-inline/transform-node.ts#L102 - defined, which node triggers the transpilation.
4. And I just thought if we could customize the place (3) and let the transformer configuration define its own custom triggers, that would allow to shorten the syntax and save 2 lines of code plus a bunch of punctuations.

I don't fully understand the library code yet, but I see that createAssertType() function just delegates its work to assertType(), so I suspect it would be somehow possible to do a custom delegation explained in (4) too.

**Comment by dko-slapdash** [comment]
@woutervh- If you're positive on this idea to let the users configure additional functions which cause the library to codegen, I can try implementing it by myself and submit a PR.

What I want to do is basically modify https://github.com/woutervh-/typescript-is/blob/master/src/transform-inline/transform-node.ts#L102 condition and add one new config options to tsconfig's `transform` object: an array of custom function- or method names which, when used in the code, trigger injection of the validation lambda. E.g. 

```
"plugins": [
  {
    "transform": "typescript-is/lib/transform-inline/transformer",
    "addMethods": ["myFunction", "RestResponse.json"]
  }
]
...
await myFunction<{ data: string }>(some); // injects the validation lambda
await get(...).json<{ data: string }>(); // injects since get() returns a RestResponse
```

I'm open to your recommendations about alternative approaches too.

**Comment by dko-slapdash** [comment]
@woutervh- so what do you think about the above? Would you be open for such a PR which adds support for recognizing custom methods (configurable in tsconfig) in addition to default assertType/createAssertType?
