### ISSUE TITLE
Obtaining type info as JSON at runtime

### ISSUE THREAD

**Issue by brettz9** [woutervh-/typescript-is#44]
Hi,

I have the following use case, and it seems your project does something pretty close, so was wondering if you might want to add it.

I've been working with the helpful CLI argument processing utility [`command-line-args`](https://github.com/75lb/command-line-args), but found it redundant to have to define what is basically a schema of definitions and then represent that same schema all over again in my jsdoc (or TypeScript) annotations.

I'd like to be able to define interfaces in TS or jsdoc, and then at runtime, pass a JSON form of these interfaces onto a utility function.

So in place of this (I don't know if your code works with jsdoc typedef's, so if not, just imagine the typedefs are interfaces or types instead):

```js
/**
 * @typedef {Object} MyCLIOptions
 * @property {boolean} v verbose
 * @property {string[]} src [default]
 * @property {number} t timeout
 */
const optionDefinitions = [
  { name: 'verbose', alias: 'v', type: Boolean },
  { name: 'src', type: String, multiple: true, defaultOption: true },
  { name: 'timeout', alias: 't', type: Number }
]
```

I'd like to be able to do something like this (I know it might not build the exact same JSON as the above array (and as a generic tool it might not parse the `[default]` text but could hopefully at least pass on the jsdoc names/descriptions), but if it could be parsed by a utility, that'd be enough):

```js
import {typeAsJSON} from 'typescript-is';
/**
 * @typedef {Object} MyCLIOptions
 * @property {boolean} v verbose
 * @property {string[]} src [default]
 * @property {number} t timeout
 */
const optionDefinitions = typeAsJSON('MyCLIOptions');

// I think I prefer the line above for being valid JS (not even needing TS), but
// possibly these if necessary?

// const optionDefinitions = typeAsJSON(MyCLIOptions);
// Or this?
// const optionDefinitions : MyCLIOptions = typeAsJSON();
```

If this is beyond your project's scope, do you have any suggestions for a novice to TypeScript?

**Comment by woutervh-** [comment]
Hi @brettz9 

A similar question was asked in #40. This question is different, but maybe you'll find the answer there useful.

At the moment I consider generating run-time type information out-of-scope. I would really like to see this from the core `typescript` package. Having such a system would make `typescript-is` way easier to implement.

I think it's possible to do what you want with transformers. I don't know if it already exists, but if a project doesn't exist for this, it sounds like a good idea for a new project.
