### ISSUE TITLE
Problem with optional properties

### ISSUE THREAD

**Issue by mvcbox** [woutervh-/typescript-is#45]
Hello!
I noticed some peculiarity when working with optional properties.
For example:
```typescript
interface SomeInterface {
    someOptionalProperty?: string;
}

const value: SomeInterface = { someOptionalProperty: undefined };
```
This code is quite valid and can be compiled without any problems.

Example with assertType:
For example:
```typescript
interface SomeInterface {
    someOptionalProperty?: string;
}

const value: SomeInterface = assertType<SomeInterface>({ someOptionalProperty: undefined });
```
In this case, I will get the error:
```
TypeGuardError: validation failed at $.someOptionalProperty: expected a string
```

**Comment by mvcbox** [comment]
@woutervh- Can you check it please?

**Comment by woutervh-** [comment]
hi @mvcbox 

This is by design. Please see #25 for more info ;)

**Comment by mvcbox** [comment]
@woutervh- ,  okay(
Thank for answer
