### ISSUE TITLE
`is` and `createIs` should error on excess properties

### ISSUE THREAD

**Issue by ArashMotamedi** [woutervh-/typescript-is#46]
Is there a way to `is` or `createIs` that errors on excess properties?

```ts
interface IPerson {
   name: string;
}

const isPerson = createIs<IPerson>();

isPerson({name: "Arash", role: "Admin" }); // this should return false, but it returns true!

```

Use case: API server receives POST message with payload in the body, performs check to make sure payload conforms to expected schema, writes object to Cosmos DB (or other no-sql Document DB). Goal would be to 1. make sure payload has the properties that the interface expects, AND 2. payload **does not** have any other/extra properties not defined in the interface. 

TypeScript itself errors on unexpected properties:

```ts
const person: IPerson = {name: "Arash", role: "Admin"}
// Type '{ name: string; role: string; }' is not assignable to type 'IPerson'.
// Object literal may only specify known properties, and 'role' does not exist in type 'IPerson'.ts(2322)
```

P.S. Big fan of `typescript-is` :)

**Comment by woutervh-** [comment]
Hi @ArashMotamedi 

Yes, this is possible.
Please check the `disallowSuperfluousObjectProperties` configuration option in the options (https://github.com/woutervh-/typescript-is#options)

**Comment by ArashMotamedi** [comment]
Excellent! Thank you @woutervh- Sorry I didn’t read the documentation fully. 

This solves my problem, so I’ll close the issue. But I do want to make a suggestion: how about adding an optional parameter to is and createIs methods to specify options on a case by case basis (in addition to the global configuration)?

Something like: 

```ts
interface IOptions {
   disallowSuperfluousObjectProperties?: boolean;
   // other options
}

function is<T>(options?: IOptions) : (object: any) => object is T;
```

**Comment by woutervh-** [comment]
Hi @ArashMotamedi 

Actually the functions you mention exist already as well :) https://github.com/woutervh-/typescript-is#strict-equality-equals-createequals-assertequals-createassertequals

Sorry, I forgot to mention it earlier!
