### ISSUE TITLE
Runtime issues when used with Jest

### ISSUE THREAD

**Issue by xogeny** [woutervh-/typescript-is#48]
I've made the changes to `jest.config.js` to use `ttypescript` and I've modified my `tsconfig.json` to use `typescript-is/lib/transform-inline/transformer` as a transform plugin.  I can compile everything fine.  But when I try to use Jest, I get:

```
This module should not be used in runtime. Instead, use a transformer during compilation.
```

I've created a repo that reproduces the issue here:

https://github.com/xogeny/siren-types

Be sure to use the **`ttypescript`** branch.

**Comment by woutervh-** [comment]
Hi @xogeny 

Unfortunately I don't use Jest so I don't really know how to configure it.
Maybe the people over in #14 know more that can help you...
All I can say is that somehow the compiler is not `ttypescript` or `ttypescript` is not enabling the `typescript-is` transformer.

I will have a glance at your repo to see if I can spot anything...

**Comment by woutervh-** [comment]
Closing for housekeeping purposes.
