### ISSUE TITLE
Incorrect behavior for nullable properties with strictNullChecks disabled

### ISSUE THREAD

**Issue by AndyBarron** [woutervh-/typescript-is#49]
When `strictNullChecks` is set to `false`, nullable properties are not allowed to be null. I suspect this is related to the TypeScript compiler transforming `string | null` to `string` in this mode. A potential fix could be allowing `null`/`undefined` for all types within `typescript-is` if it detects `strictNullChecks` are disabled?
```typescript
import { createIs } from 'typescript-is'

interface Foo {
  nullableString: string | null
}

const isFoo = createIs<Foo>()

const validFoo: Foo = {
  nullableString: null,
}

// should be true, but returns false!
console.log(isFoo(validFoo))
```

**Comment by woutervh-** [comment]
Hi @AndyBarron 

Interesting situation. I will try to find out if I can change the behavior of the type guards when `strictNullChecks` is false.

**Comment by woutervh-** [comment]
Hi @AndyBarron 

I have attempted a fix for this problem.
https://github.com/woutervh-/typescript-is/releases/tag/v0.14.2

Please try this version `0.14.2` and let me know if it works :)

**Comment by AndyBarron** [comment]
@woutervh- totally works!!! thanks so much for this, you're awesome 💪
