### ISSUE TITLE
Question - regexes on strings...?

### ISSUE THREAD

**Issue by Pikuseru** [woutervh-/typescript-is#51]
Hi there, been playing about with this library and I think it looks really good - especially as a way of defining contracts for messages between client / server.

This is probably out of scope but I thought I'd ask - it might be useful to have a way of specifying regexes on strings.

I'm not sure how that would look or work though, some custom comment syntax or decorator?

**Comment by woutervh-** [comment]
Hi @Pikuseru 

Indeed I would consider regex contracts out of scope for this library.
This library is just there for type checking.
What happens with the actual data of those types (strings) is not something I want to include in this library.

However I like the idea of defining a contract for APIs with regex validation included, so if you find such a project or decide to make one I'd like to hear about it :)

Thanks

**Comment by Pikuseru** [comment]
Okay @woutervh- - no problem - thankyou 😂 👍

**Comment by samchon** [comment]
https://github.com/samchon/typescript-json/#comment-tags

My library `typescript-json` supports it.
