### ISSUE TITLE
document how to use typescript-is without ttypescript

### ISSUE THREAD

**Issue by andykais** [woutervh-/typescript-is#54]
In my project I use webpack and I am able to use typescript-is without the ttypescript dependency. `ts-loader` has the ability to pass transformers directly into it. The following is enough to get typescript-is validators up and running.

```js
const typescriptIsTransformer = require('typescript-is/lib/transform-inline/transformer').default

module.exports = {
  // I am hiding the rest of the webpack config
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: /node_modules/,
        loader: 'ts-loader',
        options: {
          getCustomTransformers: program => ({
            before: [typescriptIsTransformer(program)]
          })
        }
      },

}
```

Just a thought if you want to drop it into your readme

**Comment by woutervh-** [comment]
Neat, I didn't know this :) Thanks, I will update the documentation.

**Comment by woutervh-** [comment]
I've added it here:
https://github.com/woutervh-/typescript-is#using-with-webpack--ts-loader-without-ttypescript

It will land on `npm` on the next release.

**Comment by andykais** [comment]
awesome! I appreciate the shoutout 
> as suggested in #54.

but dont feel like you have to, all coding is the art of `s/stealing/borrowing` ideas from others 😄. Also, another library has similar docs if you wanted a reference https://github.com/awerlogus/io-ts-transformer#webpack-with-ts-loader-or-awesome-typescript-loader. 

Im going to close this issue since my concern is addressed. Thanks again!

**Comment by woutervh-** [comment]
Oh wow, this `io-ts-transformer` looks promising too :) I think I will add a list of similar projects to the README as well

**Comment by davidmoshal** [comment]
looks like a neat solution, wondering if anyone has configured `vue.config.js` ie: to use this with vuejs ?

**Comment by rien** [comment]
@davidmoshal I'm also trying to, but it is unfortunately not working with the following config:
```js
module.exports = {
  transpileDependencies: [
    "vuetify"
  ],
  chainWebpack: config => {
    config.module
      .rule("ts")
      .use("ts-loader")
      .tap(opts => {
        opts.transpileOnly = false;
        opts.getCustomTransformers = program => ({
          before: [typescriptIsTransformer(program)],
        });
        return opts;
      });
  }
}
```
It keeps throwing the error `This module should not be used in runtime. Instead, use a transformer during compilation.`. I fear there is some other rule in the webpack config handling that piece of code.

**Comment by JacksonGariety** [comment]
I get the same runtime error at @rien on a bare webpack config. The transformation doesn't seem to happen at all. No compilation errors.

**Comment by foresightyj** [comment]
same problem here with vue-cli.

**Comment by ploth** [comment]
If I get the [vue-cli documentation](https://cli.vuejs.org/guide/webpack.html) right the way to go is to integrate @andykais snippet into the `vue.config.js` so it gets merged into the resulting `webpack.config.js` of the vue-cli setup (they are usting `webpack-merge` and `webpack-chain`).
To have a look into the resulting `webpack.config.js` just run `npx vue inspect`

```js
const typescriptIsTransformer = require('typescript-is/lib/transform-inline/transformer').default

module.exports = {
  runtimeCompiler: true,
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.ts$/,
          exclude: /node_modules/,
          loader: 'ts-loader',
          options: {
            getCustomTransformers: program => ({
              before: [typescriptIsTransformer(program)]
            })
          }
        }
      ]
    }
  },
  chainWebpack: {
    // this
  },
  devServer: {
    // and
  },
  css: {
    // that
  }
}
```

Unfortunately I run in the following errors

```
ERROR  Failed to compile with 7 errors                                                                                                                                              1:45:45 PM
                                                                                                                                                                                               
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):                                                                                                                           
Thread Loader (Worker 0)                                                                                                                                                                       
Cannot read property 'hooks' of undefined                                                                                                                                                      
    at PoolWorker.fromErrorObj (/home/ploth/projects/hunter/subprojects/app/frontendresource/vueapps/node_modules/thread-loader/dist/WorkerPool.js:262:12)                                     
    at successfulTypeScriptInstance (/home/ploth/projects/hunter/subprojects/app/frontendresource/vueapps/node_modules/ts-loader/dist/instances.js:159:27)                                     
    at Object.getTypeScriptInstance (/home/ploth/projects/hunter/subprojects/app/frontendresource/vueapps/node_modules/ts-loader/dist/instances.js:34:12)                                      
    at Object.loader (/home/ploth/projects/hunter/subprojects/app/frontendresource/vueapps/node_modules/ts-loader/dist/index.js:17:41)
...
```

Additional information
```sh
$ node --version
v11.3.0
$ npm --version   
6.4.1
```

**Comment by hmil** [comment]
@ploth Thanks for the shoutout, but I think you've credited the wrong person for your solution 😅

**Comment by ploth** [comment]
hmm, interesting :upside_down_face: 
thanks @rien !

**Comment by rolends1986** [comment]
> @davidmoshal I'm also trying to, but it is unfortunately not working with the following config:
> 
> ```js
> module.exports = {
>   transpileDependencies: [
>     "vuetify"
>   ],
>   chainWebpack: config => {
>     config.module
>       .rule("ts")
>       .use("ts-loader")
>       .tap(opts => {
>         opts.transpileOnly = false;
>         opts.getCustomTransformers = program => ({
>           before: [typescriptIsTransformer(program)],
>         });
>         return opts;
>       });
>   }
> }
> ```
> 
> It keeps throwing the error `This module should not be used in runtime. Instead, use a transformer during compilation.`. I fear there is some other rule in the webpack config handling that piece of code.

use vue3.0
1,Keep  parallel: false
2,Config chainWebpack
` parallel: false,//require('os').cpus().length > 1, on build error
  chainWebpack: config => {
    config.module
      .rule("ts")
      .use("ts-loader") 
      .tap(opts => { 
        return Object.assign(opts || {}, { 
          transpileOnly: false,
          getCustomTransformers: program => { 
            return ({
              before: [typescriptIsTransformer(program)],
            });
          }
        });
      });
  }`
