### ISSUE TITLE
Accessing the source data in TypeGuardError

### ISSUE THREAD

**Issue by dko-slapdash** [woutervh-/typescript-is#57]
TypeGuardError forms a nice error message, but the data which failed validation is not part of this error. I.e. I can catch & print "TypeGuardError: validation failed at ...", but I can't print "TypeGuardError: validation failed at ..., input data was: ..." down the stack.

Is it possible to add a field to TypeGuardError which holds the actual data failed validation? This would be super useful for debugging.

**Comment by dko-slapdash** [comment]
@woutervh- If you think it's a good idea to let the catcher TypeGuardError understand, what data caused the error, I can try implementing it by myself and submit a PR. Would be happy to contribute!

**Comment by woutervh-** [comment]
hi @dko-slapdash 

Yes, this sounds like a good idea :) It should be pretty simple to implement as well. Feel free to submit a PR!

**Comment by dko-slapdash** [comment]
Closed in https://github.com/woutervh-/typescript-is/pull/64
