### ISSUE TITLE
Tuples are not type-checked correctly

### ISSUE THREAD

**Issue by geomaster** [woutervh-/typescript-is#6]
**ttypescript version**: 3.2.4
**typescript-is version**: 0.7.18
**node version**: 11.6.0

**Steps to reproduce:**
Try compiling a file containing the following:

```typescript
import { is } from 'typescript-is';

type NumTuple = [number, number];

console.log(is<NumTuple>([0]));
console.log(is<NumTuple>([]));
```

**Actual results:**
Both statements print `true`.

**Expected results:**
Both statements should print `false`, as neither `[0]` nor `[]` satisfy the `NumTuple` type.

I feel like I'm submitting too many bug reports :) Let me know if I can help any further. Also, if there's a way to donate to the project, I'd be happy to - this is one of the most useful libraries I've used in a long time!

**Comment by woutervh-** [comment]
hi @geomaster 

I'm glad to hear you like the project. Feel free to help out with issues like this and/or PRs. The bug reports help mature the project which is good.

Back to the issue: I agree that the generated code should check for the array length of tuples, currently it just checks if it would be an array of numbers. I will fix this and release a new version.

**Comment by woutervh-** [comment]
I've added support for tuples, please check test cases here:
https://github.com/woutervh-/typescript-is/blob/master/test/issue-6.ts

New version is 0.8.0.

**Comment by woutervh-** [comment]
Closing the ticket due to house keeping, feel free to open another ticket in case it's still not working.

**Comment by geomaster** [comment]
Sorry for the delay @woutervh-, I missed the notification. Works fine now, thanks!
