### ISSUE TITLE
This library appears to be broken.

### ISSUE THREAD

**Issue by gilr47** [woutervh-/typescript-is#63]
I am using windows 10 with node 12.x.

when I clone the library, build it and run the test suite I am getting a lot of linting errors, instead of tests:

> typescript-is@0.16.0 test C:\Users\****\typescript-is
> npm run lint && npm run build && ttsc --project tsconfig-test.json && mocha

> typescript-is@0.16.0 lint :\Users\****\typescript-is
> tslint "src/**/*.ts" "test/**/*.ts"

src/transform-inline/transform-node.ts:1:1
ERROR: 1:1    linebreak-style  Expected linebreak to be 'LF'
ERROR: 2:1    linebreak-style  Expected linebreak to be 'LF'
ERROR: 3:1    linebreak-style  Expected linebreak to be 'LF'
...
and many more

also, when trying to setup the library according to your 'getting started' guide, I face lots of other errors. am I missing something?

**Comment by woutervh-** [comment]
Hi @gilr47 

The lines in the source code as correct ('LF').
Maybe your Git is configured to convert LF to CRLF when checking out?

Here's a related stackoverflow post:
https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings

Try changing to `Checkout as-is, commit as-is`
