### ISSUE TITLE
[feature request] Variant of assertType that clones object

### ISSUE THREAD

**Issue by AndyBarron** [woutervh-/typescript-is#66]
For some use cases, such as validating untrusted input, it would be nice to have a version of `assertType` that creates a new object and clones the input recursively, rather than returning the original object unmodified.

**Comment by woutervh-** [comment]
Hi @AndyBarron 

I think some existing deep clone packages will already do this very well:
https://www.npmjs.com/package/clone-deep
https://www.npmjs.com/package/deep-clone
https://www.npmjs.com/package/deepcopy

**Comment by woutervh-** [comment]
closing for house keeping
