### ISSUE TITLE
validator function crashes if it encounters BigInt

### ISSUE THREAD

**Issue by t-winter** [woutervh-/typescript-is#67]
The validation function throws a TypeError if it encounters a BigInt where it expected something else.

Example: `assertEquals<string>(BigInt(1))`

This occurs since 0.16.1 and appears to be caused by the incompatibility of `JSON.stringify()` with the BigInt data type when returning the value that was found where another type was expected.
I'd like to add that `JSON.stringify()` has other issues (most notably incompatibility with circular references).

I suggest using `util.inspect()` if available (i.e. when used in a node environment) and `JSON.stringify()` in a try/catch block if not (and either omit the encountered object or print it directly to the console with `console.dir()` on errors).

**Comment by woutervh-** [comment]
Hi @t-winter 

Thanks for the detailed report. Indeed `JSON.stringify` does not seem to be able to handle `BigInt` types, among other things.

Your suggestion to use `util.inspect` when possible and wrapping `JSON.stringify` with a `try/catch` sounds like a good solution.

I will update this issue when I've published a fix :)

**Comment by woutervh-** [comment]
Released fix
https://github.com/woutervh-/typescript-is/releases/tag/v0.16.3

Test file
https://github.com/woutervh-/typescript-is/blob/master/test/issue-67.ts
