### ISSUE TITLE
Unable to throw Custom TypeGuardError. Type validation fails

### ISSUE THREAD

**Issue by rashid301** [woutervh-/typescript-is#74]
It seems the typescript declaration of TypeGuardError is missing the actual constructor.

When I do `throw new TypeGuardError(errorObject, inputObject)`, typescript pickups the constructor of Error object and allows only one message argument. But the definition requires `errorObject` and `inputObject`

Definition https://github.com/woutervh-/typescript-is/blob/master/index.js#L34
Declaration https://github.com/woutervh-/typescript-is/blob/master/index.d.ts#L167

**Comment by woutervh-** [comment]
Thanks @rashid301 

I will release a fix for this soon.

**Comment by woutervh-** [comment]
Done!

https://github.com/woutervh-/typescript-is/releases/tag/v0.17.0

**Comment by rashid301** [comment]
Thank you. I can confirm the issue is resolved in the new version.
