### ISSUE TITLE
Method param-type assertions error when earlier params have no decorator

### ISSUE THREAD

**Issue by Venryx** [woutervh-/typescript-is#75]
The approach for adding runtime type-assertions for class-method params (using `@AssertType()`), fails when there are params without that decorator earlier in the param list.

Reproduction: (needs the [decorator setup here](https://github.com/woutervh-/typescript-is#decorators-validateclass-and-asserttype), of course)
```
@ValidateClass()
class Class1 {
	Test1(firstParam: string, @AssertType() secondParam: string) {
	}
}
const classInstance = new Class1();
classInstance.Test1(1, 2);
```

Running the above gives the following error:
```
TypeError: Cannot read property 'assertion' of undefined
```

The line that errors is here: https://github.com/woutervh-/typescript-is/blob/master/index.js#L62

The fix should be as simple as changing this line:
```
const errorObject = assertions[i].assertion(args[i]);
```

To these lines:
```
if (assertions[i] == null) continue;
const errorObject = assertions[i].assertion(args[i]);
```

**Comment by Venryx** [comment]
A temporary workaround is to add the `@AssertType()` decorator to the earlier params, but just mark their type as `any`.

However, the fix given in the OP would be better, as some people might want a custom type for earlier params, but just not have runtime checking of it. (also, it is unexpected for library users that placing a decorator on one param would require you to add it to all the previous ones as well)

**Comment by woutervh-** [comment]
Thanks @Venryx for the report and a fix as well!

I will release this soon.

**Comment by woutervh-** [comment]
Done!

https://github.com/woutervh-/typescript-is/releases/tag/v0.17.0
