### ISSUE TITLE
Unbound type parameter error for interface extending type

### ISSUE THREAD

**Issue by davidfurey** [woutervh-/typescript-is#86]
When you extend a generic interface, typescript-is correctly identifies that you have bound the type parameter.  If instead you extend a generic type alias, typescript-ts throws the error `Unbound type parameter, missing type node.`

### Example with error
```
type Y<T> = {
    field: T;
}

interface X extends Y<string> { }

is<X>({ field: 'some-string' })
```
### Example without error
```
interface Y<T> {
    field: T;
}

interface X extends Y<string> { }

is<X>({ field: 'some-string' })
```

**Comment by woutervh-** [comment]
Thanks again for the PR, @davidfurey 

Release: https://github.com/woutervh-/typescript-is/releases/tag/v0.17.1
