### ISSUE TITLE
support template literal types

### ISSUE THREAD

**Issue by DetachHead** [woutervh-/typescript-is#91]
https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html

**Comment by DetachHead** [comment]
i'm giving this a shot https://github.com/DetachHead/typescript-is

**Comment by DetachHead** [comment]
some things to consider:
- template literal types that only contain unions and/or booleans evaluate to unions of all possible string combinations. in cases like this, typescript-is already supports it because the type it evaluates to is just a regular union
- template literal types that contain `${string}`, `${number}`, etc. are implemented in such a way that leads to [some unexpected behavior](https://github.com/microsoft/TypeScript/issues/42903#issuecomment-784366198).
    - what should the compiled functions look like? i believe those problems could be easily solved if regex was used in place of the placeholders. for example, ``is<`foo${string}${number}bar`>`` would compile to something like
        ```js
            function _3660(object) {
            ;
            if (object.match(/foo.*\dbar/))
                return {
                    message: "validation failed at " + path.join(".") + ": expected template literal 'foo${string}${number}bar'",
                    path: path.slice(),
                    reason: {type: "string-literal", value: "foo${string}${number}bar"}
                };
            else
                return null;
        }
        ````
        though this would mean the type checker behaves differently to the typescript compiler, which i imagine is not desired. in that case the generated regex could look like `/foo.\dbar/`
   - is regex even an efficient solution? maybe it should just look ahead like the compiler does.

@woutervh- any advice?

**Comment by DetachHead** [comment]
i went with treating the values the same way the compiler does

**Comment by woutervh-** [comment]
Thanks again.
Release `v0.18.0` https://github.com/woutervh-/typescript-is/releases/tag/v0.18.0
